name: flutter_inappwebview

publish_to: 'none' # Optional, to prevent accidental publishing

version: 6.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview:
    path: ./flutter_inappwebview

dependency_overrides:
  flutter_inappwebview_platform_interface:
    path: ./flutter_inappwebview_platform_interface
  flutter_inappwebview_internal_annotations:
    path: ./dev_packages/flutter_inappwebview_internal_annotations
  generators:
      path: ./dev_packages/generators

dev_dependencies:
  flutter_test:
    sdk: flutter


